### ISSUE TITLE
occupancy label

### ISSUE THREAD

**Issue by raozhongyu** [SPengLiang/OccupancyM3D#8]
你好，感谢博主的精彩工作，我想问一下，如果想用自己的数据复现代码，其中的occupancy label是如何生成的呢

**Comment by SPengLiang** [comment]
你好，如果是自己的数据，可以直接用lidar点与camera的位置来生成occupancy label，我们在image_vfe中提供了一个实现。

**Comment by raozhongyu** [comment]
好的感谢



发自我的iPhone


------------------ Original ------------------
From: SPengLiang ***@***.***&gt;
Date: Sat,Aug 5,2023 8:07 PM
To: SPengLiang/OccupancyM3D ***@***.***&gt;
Cc: raozhongyu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SPengLiang/OccupancyM3D] occupancy label (Issue #8)





 
你好，如果是自己的数据，可以直接用lidar点与camera的位置来生成occupancy label，我们在image_vfe中提供了一个实现。
